import 'package:flutter/material.dart';

class MyColor {
  static final Color white = Color(0xFFFFFFFF);
  static final Color red = Color(0xFFFD4A4E);
  static final Color blue = Color(0xFF31C7F5);
  static final Color bluefb = Color(0xFF1FFF);
  static final Color violetfb = Color(0xFF1F6CFF);
  static final Color blue_bg = Color(0xFFE7F0F5);
  static final Color blue_accent = Color(0xFF0082be);
  static final Color red_bg_opacity = Color(0xFFFD4A4E).withOpacity(0.075);
  static final Color red_accent = Color(0xFFBD373A);
  static final Color red_pink_bg = Color(0xFFFEF6F8);
  static final Color grey = Color(0xFF8F8F8F);
  static final Color grey_background_blur = Color(0xFFFAFAFA);
  static final Color grey_background_blur2= Color(0xFFF5F5F5);
  static final Color grey_line = Color(0xFFF5F5F5);
  static final Color green = Color(0xFF1ECB5D);
  static final Color green_accent = Color(0xFF598066);
  static final Color green2 = Color(0xFF1ECB59);
  static final Color white_text = Color(0xFFFFFFFF);
  static final Color black_text = Color(0xFF2D2D2D);
  static final Color grey_text = Color(0xFF8F8F8F);
  static final Color red_text = Color(0xFFFD4A4E);
  static final Color yellow = Color(0xFFFAD932);
  static final Color yellow_accent = Color(0xFFB2A76B);
  static final Color orange = Color(0xFFFE9433);
  static final Color pink = Color(0xFFFFC0CB);
  static final Color orange_accent = Color(0xFFA87954);
  static final Color red_bg = Color(0xFFFEF6F8).withOpacity(0.75);
  static final Color grey_tab = Color(0xFFE0E0E0);
  static final Color grey_tab3= Color(0xFFD6D6D6);
  static final Color grey_tab2 = Color(0xFFF5F5F5);
  static final Color grey_icon = Color(0xFFE0E0E0);
  static final Color dialog = Color(0xFFCAD3DE).withOpacity(0.5);
  static final Color dialog2 = Color(0xFF8F8F8F).withOpacity(0.5);
  static final Color violet = Color(0xFF7D3C98).withOpacity(0.5);
  static final Color darkBlue = Color(0xFF34495E).withOpacity(0.5);
  static final Color greyCham = Color(0xFF99A3A4).withOpacity(0.5);
}